# Generated by Django 5.1.4 on 2025-01-07 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id_filiere', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id_photo', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/')),
                ('description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id_prof', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prof', models.CharField(max_length=50)),
                ('prenom_prof', models.CharField(max_length=50)),
                ('specialite_prof', models.CharField(max_length=150)),
                ('image_prof', models.ImageField(upload_to='prof_photos/')),
                ('adresse_prof', models.CharField(max_length=100)),
                ('telephone_prof', models.CharField(max_length=50)),
                ('email_prof', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom_user', models.CharField(max_length=50)),
                ('prenom_user', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('actif', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_etudiant', models.AutoField(primary_key=True, serialize=False)),
                ('nom_etu', models.CharField(max_length=50)),
                ('prenom_etu', models.CharField(max_length=50)),
                ('email_etu', models.EmailField(max_length=100)),
                ('image_etu', models.ImageField(upload_to='etudiant_photos/')),
                ('telephone_etu', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutapp.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='LienSociale',
            fields=[
                ('id_lien', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50)),
                ('lien', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutapp.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id_sout', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=255)),
                ('Heure_deb', models.TimeField(blank=True, null=True)),
                ('Heure_fin', models.TimeField()),
                ('Date_sout', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('is_finish', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutapp.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id_rapport', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('sommaire', models.TextField()),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_sout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutapp.soutenance')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('sujet', models.CharField(max_length=100)),
                ('email_user', models.EmailField(max_length=255, unique=True)),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Apprecier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appreciation', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('id_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutapp.professeur')),
                ('id_sout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutapp.soutenance')),
            ],
            options={
                'unique_together': {('id_sout', 'id_prof')},
            },
        ),
        migrations.CreateModel(
            name='SoutenanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pour', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutapp.photo')),
                ('id_sout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutapp.soutenance')),
            ],
            options={
                'unique_together': {('id_sout', 'id_photo')},
            },
        ),
        migrations.CreateModel(
            name='Superviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('id_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutapp.professeur')),
                ('id_sout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutapp.soutenance')),
            ],
            options={
                'unique_together': {('id_sout', 'id_prof')},
            },
        ),
    ]
