# Generated by Django 5.1.4 on 2025-01-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soutapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id_user',
        ),
    ]
