# Generated by Django 5.1.4 on 2025-01-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutapp', '0002_remove_message_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
