# Generated by Django 5.1.4 on 2025-01-07 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soutapp', '0003_alter_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='actif',
        ),
    ]
