# Generated by Django 5.1.4 on 2025-01-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutapp', '0004_remove_utilisateur_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
