# Generated by Django 5.1.4 on 2025-01-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutapp', '0005_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
