# Generated by Django 5.1.4 on 2025-01-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soutapp', '0006_utilisateur_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
