# Generated by Django 5.1.4 on 2025-01-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutapp', '0007_delete_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email_user',
            field=models.EmailField(max_length=255),
        ),
    ]
